title: Tanishq Chakravorty
description: Language Scientist
markdown: kramdown
github:
  is_project_page: false
show_downloads: false
theme: jekyll-theme-midnight
plugins: 
  - jekyll-feed
include: [assets]
