title: Tanishq Chakravorty
description: Language Scientist
email: "tanishq.chakravorty@unine.ch"
cv_url: "https://yourwebsite.com/path/to/your/cv.pdf"
github:
  is_project_page: false
show_downloads: false
theme: jekyll-theme-midnight
include: [./assets/css/style.scss]
